networks:
# The presence of these objects is sufficient to define them 
  expense: {}
volumes: 
 mysql:
services:

  backend:
     image: backend:1.0.0
     networks:
     - expose:
     container_name: backend
     depends_on:
      - mysql
# docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql:
   image: mysql:1.0.0 
   networks:
   - expense 
   container_name: mysql
   volumes:
   - mysql:/var/lib/mysql 

   backend:
     image: backend:1.0.0
     networks:
     - expose:
     container_name: backend
     depends_on:
      - mysql

     frontend:
       image: frontend:1.0.0 
       networks:
       - expense
       container_name: frontend
       ports:
       - 80:80
       depends_on:
       - backend
